### ISSUE TITLE
1.20.2 server start Error

### ISSUE THREAD

**Issue by FormulaAbyss** [John-Paul-R/kits#22]
### Expected behavior

No error on startup

### Observed/actual behavior

See error below

### Steps/models to reproduce

31.10 09:41:41 [Server] main/ERROR Mixin apply for mod kits failed kits.mixins.json:PlayerManagerMixin from mod kits -> net.minecraft.class_3324: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on kits.mixins.json:PlayerManagerMixin from mod kits->@Inject::onPlayerConnect(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lnet/minecraft/class_8792;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> kits.mixins.json:PlayerManagerMixin from mod kits -> Apply Injections ->  -> Inject -> kits.mixins.json:PlayerManagerMixin from mod kits->@Inject::onPlayerConnect(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
31.10 09:41:41 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on kits.mixins.json:PlayerManagerMixin from mod kits->@Inject::onPlayerConnect(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lnet/minecraft/class_8792;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> kits.mixins.json:PlayerManagerMixin from mod kits -> Apply Injections ->  -> Inject -> kits.mixins.json:PlayerManagerMixin from mod kits->@Inject::onPlayerConnect(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.23.jar:?]
31.10 09:41:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.23.jar:?]
31.10 09:41:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.23.jar:?]
31.10 09:41:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.23.jar:?]
31.10 09:41:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
31.10 09:41:41 [Server] INFO at net.minecraft.server.Main.method_29734(Main.java:222) ~[server-intermediary.jar:?]
31.10 09:41:41 [Server] INFO at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:270) ~[server-intermediary.jar:?]
31.10 09:41:41 [Server] INFO at net.minecraft.server.Main.main(Main.java:221) ~[server-intermediary.jar:?]
31.10 09:41:44 [Multicraft] Skipped 37 lines due to rate limit (30/s)
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
31.10 09:41:44 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.23.jar:?]
31.10 09:41:44 [Server] INFO ... 12 more

### Version

1.6.0-ms1.20.2

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by arnokeesman** [comment]
The mod didn't get updated all the way, it's been fixed since, just not released yet, you can grab it from [the action artifactifacts](https://github.com/John-Paul-R/kits/suites/17710879269/artifacts/1013882576)
(for anyone lurking without being logged in and getting a 404, log in)
